data:
  input_dir: ./rag/data/corpus

components:
  chunking:
    chunk_size: 800
    chunk_overlap: 120
  embedding:
    type: tfidf              # tfidf | sbert
    max_features: 50000
    ngram_range: [1, 2]
  index:
    type: cosine            # cosine | faiss
  generator:
    type: template          # template | openai
    template_path: ./rag/prompts/qa.jinja
  reranker:
    type: none              # none | cross_encoder
    model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
    device: cpu

retriever:
  type: hybrid              # dense | bm25 | hybrid
  top_k: 8
  alpha: 0.6


